project:
  type: website

website:
  title: "SCENES Dataset"
  site-url: https://scenes-dataset.org/
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Data at a Glance"
        href: stats.qmd
      - text: "Download"
        href: download.qmd
      - text: "Gallery"
        href: gallery.qmd
      - text: "Documentation"
        href: documentation.qmd
  page-footer:
    center: |
      [![](assets/logo-mpi.png){width=180pt}](https://www.kyb.tuebingen.mpg.de/en)
    right: "[Imprint](imprint.qmd)"

format:
  html:
    include-in-header: assets/plotly-loader.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lightbox: true

execute:
  freeze: auto

date: last-modified

language:
  title-block-published: "Last modified:"